# $schema: https://github.com/mason-org/registry-schema/releases/latest/download/package.schema.json
---
name: composefmt
description: a simple docker compose formatter
homepage: https://pypi.org/project/composefmt/
licenses:
  - CC-BY-SA-4.0
languages:
  - Python
categories:
  - Formatter

source:
  id: pkg:pypi/composefmt@0.3.2
bin:
  composefmt: pypi:composefmt
